#cloud-config
password: {{ users.ubuntu.password }}
chpasswd: { expire: False }
users:
        - default
        - name: gns3
          primary_group: gns3
          password: {{ users.gns3.password }}
          groups: users,libvirt,kvm
          shell: /bin/bash
          # sudo: ['ALL=(ALL) NOPASSWD:ALL']

ssh_pwauth: True
apt_sources:
        - source: "ppa:gns3/ppa"
package_upgrade: true
packages:
- gns3-server
#- vim
write_files:
        - path: /etc/apt/apt.conf.d/02proxy
          permissions: 0644
          owner: root:root
          content: |
                Acquire::http::Proxy "http://{{ proxy_server.ip }}:{{ proxy_server.port }}/";
        # https://github.com/GNS3/gns3-server/blob/master/init/gns3.service.systemd
        - path: /lib/systemd/system/gns3.service
          permissions: 0644
          owner: root:root
          content: |
                [Unit]
                Description=GNS3 server
                Wants=network-online.target
                After=network.target network-online.target

                [Service]
                Type=forking
                User=gns3
                Group=gns3
                PermissionsStartOnly=true
                ExecStartPre=/bin/mkdir -p /var/log/gns3 /var/run/gns3
                ExecStartPre=/bin/chown -R gns3:gns3 /var/log/gns3 /var/run/gns3
                ExecStart=/usr/bin/gns3server --log /var/log/gns3/gns3.log --pid /var/run/gns3/gns3.pid --daemon
                Restart=on-abort
                PIDFile=/var/run/gns3/gns3.pid

                [Install]
                WantedBy=multi-user.target
        - path: /home/ubuntu/gns3_server.conf
          permissions: 0644
          owner: root:root
          content: |
                [Server]
                auth = True
                user = gns3
                password = madabeta

runcmd:
        #        - [ apt, -y, purge, ubuntu-advantage-tools ]
        #        - [ apt, clean ]
        #        - [ apt, update ]
        #        - [ apt, -y, upgrade ]
        #        - [ apt, -y, install, gns3-server ]
        - [ systemctl, enable, gns3.service ]
        - [ systemctl, start, gns3.service ]
        - [ chmod, +x, /usr/bin/ubridge ]
        - [ adduser, gns3, ubridge ]
        - [ systemctl, restart, gns3.service ]
        - [ mkdir, -p, /home/gns3/.config/GNS3 ]
        - [ cp, /home/ubuntu/gns3_server.conf, /home/gns3/.config/GNS3/ ]
        - [ sh, -c, "chown -R gns3:gns3 /home/gns3/.config" ]
        - [ sh, -c, "chown -R ubuntu:ubuntu /home/ubuntu" ]
power_state:
        delay: "+1"
        mode: reboot
        message: Bye Bye
        timeout: 30

