version: 1
config:
  - type: nameserver
    address:
      - {{ dns_ip }}
  - type: physical
    name: enp0s2
    subnets:
     - control: auto
       type: static
       address: {{ ip }}
       gateway: {{ gateway }}
